#!/usr/bin/env python3
"""
Write a multi-element ugur potential file from the pure-element library.

The format is LAMMPS's Tersoff convention: one line per ordered triple
(centre, leg, leg), N**3 lines for N elements, and two-body parameters read
only from the lines where the two legs agree.  See ALLOYS.md for why the
problem has that shape - phi3 depends on the legs through r1 + r2 and does not
factorise, so C and alpha3 belong to a triple and cannot be built out of pair
quantities.

The mixing rules here are conventional and **none of them is validated**.  They
are written into the header of every file produced, so that whoever is holding
one does not have to come back here to find out what it assumes.  The intended
use is as a starting point for a fit against alloy data, with the refitted
unlike entries written straight back into the same file.

    python make_alloy_file.py Cu Ni > CuNi.ugur.alloy
    python make_alloy_file.py --set tap Cu Ni Al

`--set tap` uses the tapered parameters, which is what anything going into MD
should use; the default is the hard-truncated reference set.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

PAIR = ("m", "D", "alpha", "r0", "gamma")
CUT = ("rcut2", "rcut3")


def geometric(vals):
    """|product|**(1/n), which is the geometric mean where signs allow"""
    p = 1.0
    for v in vals:
        p *= abs(v)
    return p ** (1.0 / len(vals))


def arithmetic(vals):
    return sum(vals) / len(vals)


def mix_pair(a, b):
    """parameters for the A-B bond from the two pure elements"""
    out = {}
    #  a well depth multiplies, a length adds: the Lorentz-Berthelot split,
    #  which is a convention and not a derivation
    out["D"] = geometric([a["D"], b["D"]])
    out["r0"] = arithmetic([a["r0"], b["r0"]])
    out["alpha"] = arithmetic([a["alpha"], b["alpha"]])
    #  m and gamma are exponents with no dimensional argument either way
    out["m"] = arithmetic([a["m"], b["m"]])
    out["gamma"] = arithmetic([a["gamma"], b["gamma"]])
    #  cutoffs average so that the switch window stays the same fraction of
    #  the range for every bond
    for k in CUT:
        out[k] = arithmetic([a[k], b[k]])
    return out


def mix_triple(recs):
    """C and alpha3 for a triple, given (centre, leg, leg) records

    The sign of C is taken from the centre rather than from the product.  C
    changes sign across this library, so a geometric mean is undefined where
    the product is negative, and the centre is the atom whose bonds are being
    bent.  It is a convention; ALLOYS.md says so and says it can be argued
    with.
    """
    cs = [r["C"] for r in recs]
    sign = -1.0 if recs[0]["C"] < 0 else 1.0
    return {"C": sign * geometric(cs),
            "alpha3": arithmetic([r["alpha3"] for r in recs])}


HEADER = """\
# Ugur potential, {n} elements: {els}
# Generated by make_alloy_file.py from the {which} parameter set.
#
# FORMAT - LAMMPS Tersoff convention.  One line per ordered triple
# (centre, leg, leg).  Two-body parameters are read ONLY from the lines where
# the two legs agree; elsewhere they are repeated for readability and ignored.
# Three-body parameters (C, alpha3) are read from every line.
#
#   el1 el2 el3   m  D  alpha  r0  gamma  C  alpha3  rcut2  rcut3  taper \
lam2 lam4
#
# UNLIKE ENTRIES ARE NOT FITTED.  They come from these rules and nothing has
# tested them:
#   D_AB      = sqrt(D_A D_B)          r0_AB     = (r0_A + r0_B)/2
#   alpha_AB  = (alpha_A + alpha_B)/2  m, gamma  = arithmetic mean
#   rcut_AB   = arithmetic mean        taper     = must be identical
#   C_ABC     = |C_A C_B C_C|^(1/3), sign of the centre's C
#   alpha3_ABC= arithmetic mean of the three
#
# Only C and alpha3 are read from a triple line.  phi3's radial shape - D, m,
# r0, gamma - is taken from the CENTRE element's own (A,A,A) entry, because a
# triple must be symmetric under swapping its legs and the (A,B,C) and (A,C,B)
# lines carry different pair columns.  The pair columns therefore serve phi2
# alone and are not doing double duty.
# Like entries (el1 = el2 = el3) are the fitted pure-element parameters and are
# exact.  Treat an alloy built from this file as a starting point for a fit,
# not as a prediction.  See ALLOYS.md.
"""


def main():
    args = sys.argv[1:]
    which = "hard-truncated"
    if "--set" in args:
        i = args.index("--set")
        which = "tapered" if args[i + 1] == "tap" else args[i + 1]
        del args[i:i + 2]
    if len(args) < 2:
        raise SystemExit("two or more elements are required, for example: "
                         "python make_alloy_file.py Cu Ni")

    lib = json.load(open(os.path.join(ROOT, "standalone", "library.json")))
    recs = {}
    for el in args:
        if el not in lib:
            raise SystemExit(f"{el} is not in the library")
        r = lib[el]["tap"] if which == "tapered" else lib[el]
        if which == "tapered" and not r:
            raise SystemExit(f"no tapered record for {el}")
        recs[el] = r

    tapers = {r.get("taper") or -1.0 for r in recs.values()}
    if len(tapers) > 1:
        raise SystemExit(f"the elements carry different tapers: {tapers}; "
                         "pencere modelin parcasi, bag basina parametre degil")
    taper = tapers.pop()

    out = [HEADER.format(n=len(args), els=" ".join(args), which=which)]
    for a in args:
        for b in args:
            pb = mix_pair(recs[a], recs[b]) if a != b else dict(recs[a])
            for c in args:
                tri = (mix_triple([recs[a], recs[b], recs[c]])
                       if not (a == b == c) else
                       {"C": recs[a]["C"], "alpha3": recs[a]["alpha3"]})
                v = [pb["m"], pb["D"], pb["alpha"], pb["r0"], pb["gamma"],
                     tri["C"], tri["alpha3"], pb["rcut2"], pb["rcut3"],
                     taper, 0.0, 0.0]
                out.append(f"{a:<3s} {b:<3s} {c:<3s} "
                           + " ".join(f"{x:.12g}" for x in v))
    print("\n".join(out))


if __name__ == "__main__":
    main()
